// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1_-EaBQ5uHPRLvFgDCffON8Twesxdg8o',
    appId: '1:551604259887:android:b68a85d51191899d3a4ada',
    messagingSenderId: '551604259887',
    projectId: 'fooddelivery-52ab2',
    storageBucket: 'fooddelivery-52ab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBH76Zvg3eXojgx6uw--9slADnqXe6DuA',
    appId: '1:551604259887:ios:c903eb75b8cc561c3a4ada',
    messagingSenderId: '551604259887',
    projectId: 'fooddelivery-52ab2',
    storageBucket: 'fooddelivery-52ab2.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliverApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF-szKP8hdgwqyXaaoYsirqERITXbBYDg',
    appId: '1:551604259887:web:087af0f04d8c4bfd3a4ada',
    messagingSenderId: '551604259887',
    projectId: 'fooddelivery-52ab2',
    authDomain: 'fooddelivery-52ab2.firebaseapp.com',
    storageBucket: 'fooddelivery-52ab2.firebasestorage.app',
    measurementId: 'G-LCX7J5Q90Q',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF-szKP8hdgwqyXaaoYsirqERITXbBYDg',
    appId: '1:551604259887:web:5530353f515165a73a4ada',
    messagingSenderId: '551604259887',
    projectId: 'fooddelivery-52ab2',
    authDomain: 'fooddelivery-52ab2.firebaseapp.com',
    storageBucket: 'fooddelivery-52ab2.firebasestorage.app',
    measurementId: 'G-R569EZ821D',
  );

}